GET {{host}}/v1/expense/paid/info
Accept: application/json
Authorization: 7801152fcf6e5dae2a15d9dab904203a

###
GET {{host}}/v1/expense/approvals
Accept: application/json
Authorization: 8c087c137126cf0b673ada443e7b963e
###

GET {{host}}/v1/expense/projects
Accept: application/json
Authorization: 8c087c137126cf0b673ada443e7b963e
###

POST {{host}}/v1/login
Content-Type: application/json

{
  "username":"qianqian.niu",
  "password": "123"
}

### 登陆员工

POST {{host}}/v1/login
Content-Type: application/json

{
  "username":"lie.chen",
  "password": "123"
}

### 登陆负责人

POST {{host}}/v1/login
Content-Type: application/json

{
  "username":"kaili.wang",
  "password": "123"
}

### 登陆财务


GET {{host}}/v1/expense/12
Content-Type: application/json
Authorization: 8c087c137126cf0b673ada443e7b963e

###
POST {{host}}/v1/expense
Content-Type: application/json
Authorization: 6796f471e2c886bb27b063a8a32814bc

{
  "engagement_code": "",
  "expense_details": [
    {
      "ID": 0,
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z",
      "DeletedAt": null,
      "expense_id": 0,
      "expense_account_code": "10010",
      "expense_account": {
        "ID": 0,
        "CreatedAt": "0001-01-01T00:00:00Z",
        "UpdatedAt": "0001-01-01T00:00:00Z",
        "DeletedAt": null,
        "expense_account_code": "10010",
        "expense_account_name": "交通费(市外)"
      },
      "ocurred_date": "2006-01-02",
      "expense_amount": 11,
      "remarks1": "1",
      "remarks2": "1",
      "remarks3": ""
    },
    {
      "ID": 0,
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z",
      "DeletedAt": null,
      "expense_id": 0,
      "expense_account_code": "10010",
      "expense_account": {
        "ID": 0,
        "CreatedAt": "0001-01-01T00:00:00Z",
        "UpdatedAt": "0001-01-01T00:00:00Z",
        "DeletedAt": null,
        "expense_account_code": "10010",
        "expense_account_name": "交通费(市外)"
      },
      "ocurred_date": "2006-01-02",
      "expense_amount": 100.11,
      "remarks1": "1",
      "remarks2": "",
      "remarks3": ""
    }
  ],
  "project": "云测",
  "import_file": "12121.xlsx",
  "leader_id": 12

}

### 申请报销

GET {{host}}/v1/expense?userEmail=11111112@qq.com&searchid=1&application_date_begin=2020-12-01 15:14:14&application_date_end=2020-12-30 15:14:14
Accept: application/json

### 报销列表

GET {{host}}/v1/expense?mytodo=true
Accept: application/json
Authorization: a5550694abf5e184242678d7f26c4833

### 报销列表 审核

GET {{host}}/v1/expense?mytodo=true&todostatus=1
Accept: application/json
Authorization: e3312b5a292c5c5085243eca5b548202

### 报销列表 报销


GET {{host}}/v1/expense/approvals?userEmail=kaili.wang@broadfun.cn
Accept: application/json


### 报销审核人
POST {{host}}/v1/expense/details
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: 6796f471e2c886bb27b063a8a32814bc

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="excel.xlsx"

< tmp/t.xlsx
--WebAppBoundary--

### 解析报销xlsx文件
